baseurl = "http://golang.org.ua/"
languageCode = "en-us"
title = "GolangUA"
paginate = 5
theme = "hyde"
[params]
  description = "Ukrainian Golang User Group"
  hideHUGOSupport = false
  themeColor = "theme-base-0c"
  disqusShortname = "golangua"
