baseurl = "https://golang.org.ua/"
languageCode = "en-us"
title = "GolangUA"
paginate = 5
theme = "hyde"
googleAnalytics = "UA-29109282-4"
[params]
  description = "Ukrainian Golang User Group"
  hideHUGOSupport = false
  themeColor = "theme-base-0c"
  disqusShortname = "golangua"
  facebookURL = "https://www.facebook.com/groups/GolangUA/"
  githubURL = "https://github.com/GolangUA"
  youtubeURL = "https://www.youtube.com/channel/UCpBO9AEA0kb7agq7dxT0dsA"
  twitterURL = "https://twitter.com/GolangUA"
  slackURL = "http://gophers.in.ua/"
